version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - fastapi
    env_file:
      - .env
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge